export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";
export const SEARCH_USER_START = "SEARCH_USER_START";
export const RESET_SEARCH = "RESET_SEARCH";
export const FETCH_REPO = "FETCH_REPO";
